singly_linked_list.out: main_sll.c singly_linked_list.o
	gcc -o singly_linked_list.out main_sll.c singly_linked_list.o

singly_linked_list.o: singly_linked_list.c

.PHONY: clean
clean:
	rm *.o singly_linked_list.out
